### ISSUE TITLE
Diseñar Sección Quiénes Somos

### ISSUE THREAD

**Issue by danielhernandezs** [BrandSpa/acninternational.org#5]
Referencia:   http://www.arautos.org/ajude/

[ HEADER ] : Aquí colocamos un resumen de la ayuda de la fundación, un ejemplo abajo, extractado de la página de España.
[ TIPO DE AYUDA 1 ]
  Foto en background
  ícono, Título
  Texto resumen
[ TIPO DE AYUDA ... N ]
[ FOOTER ]

Adicional:  Agregar un banner, que SOLO DEBE SALIR EN LA VERSION INTERNACIONAL ( cuando vengo de un país sin oficina ), donde invitamos a donar.

![image](https://cloud.githubusercontent.com/assets/26444890/23972671/a91edc6e-09a0-11e7-9b1d-104b3b6a636d.png)

QUIEN SOMOS DETALLE:
Esto pasa cuando alguien hace click en cualquier de las secciones:

[ HEADER ] 
   TITULO
   TEXTO RESUMEN
[RESUMEN AYUDA]
  Esto es un resumen en cifras de la ayuda dada en este topic
[POSTS RELACIONADOS]
  Noticias o videos relacionados con el topic ( las escogemos de las noticias publicadas )
[ FOOTER ]

AGREGAR BANNER PIDIENDO AYUDA TAMBIÉN ( solo para la versión internacional ).

**Comment by MoniLop** [comment]
enviada version mobile al cliente, pendiente de aprobación

**Comment by MoniLop** [comment]
Aprobado, Haciendo maqueta en WordPress
