### ISSUE TITLE
Diseñar sección GRANTS GUIDELINES

### ISSUE THREAD

**Issue by danielhernandezs** [BrandSpa/acninternational.org#6]
PRIMERO MOBILE

Esta sección está dirigida a los "project partners" o las personas que desean solicitarnos ayuda.  Esta no es una sección de alto tráfico, pero es una sección que requiere estar disponible;  es muy importante para el departamento de proyectos.

Se quiere que sea igualita a la versión que hoy en día existe: 
http://www.acn-intl.org/pg/grants.html?p=EN,11,13,,1,

La versión 1 debe ser lo más idéntica a la que existe hoy, respetando el design que estamos haciendo del website.

AQUÍ NO COLOCAR ESPACIO PARA PEDIR DONACIÓN.

**Comment by MoniLop** [comment]
enviada version mobile al cliente, pendiente de aprobación

**Comment by MoniLop** [comment]
Diego:

Preliminarmente esta aprobada esta sección. Solo me pidieron no vincularla al menú, ni publicarla hasta q los del project department la vean. Me mandas entonces una URL temporal cuando esté montada. 

(Esta en proceso de maquetación en WordPress)
